server:
  port: 9002
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: BBS-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_sale?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 137238fh
  jackson:
    time-zone:
      GMT+8
  web:
    resources:
      static-locations: file:asset
mybatis:
  mapper-locations: classpath:/mapper/*xml
