server:
  port: 8082
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: bbs-service
          uri: lb://BBS-SERVICE
          predicates:
            - Path=/moment/**,/comment/**
        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/after_sale_order/**,/sale_order/**,/car/**,/test_drive/**,/user/**
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
logging:
  level:
    reactor:
      netty:
        DEBUG